name: mdcdavan
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.0
  async: ^2.0.8

dev_dependencies:
  test: ^1.0.0
